version: '3'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        depends_on:
            - db
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./.docker/.config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./.docker/.config/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - app-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "84:84"
        volumes:
            - ./:/var/www
            - ./.docker/.config/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    #MySQL Service
    db:
        image: postgres:13.3
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: napopravku
            POSTGRES_USER: napopravku
            POSTGRES_PASSWORD: napopravku
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
